connection: &connection
  adapter: postgresql
  encoding: utf8
  host:     localhost
  pool: 5


development:
  <<: *connection
  database: classes-aggregator_development
  username: <%= ENV['APP_POSTGRES_USER'] %>
  password: <%= ENV['APP_POSTGRES_PASSWORD'] %>

test: &test
  <<: *connection
  database: classes-aggregator_test
  username: <%= ENV['APP_POSTGRES_USER'] %>
  password: <%= ENV['APP_POSTGRES_PASSWORD'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
